[package]
name = "aoc-2020-rust"
version = "0.1.0"
authors = ["Eshan <eshansingh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
itertools = "0.9"
clap = "2.33"